apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: faasm
spec:
  selector:
    role: upload
  type: LoadBalancer
  externalIPs:
    - 20.42.32.116
  ports:
    - port: 8002
      targetPort: 8002
