---

- name: "System deps"
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - pass
      - software-properties-common
      - linux-generic-hwe-20.04
    update_cache: yes

- name: "Clone faasm repo"
  git:
    repo: "https://www.github.com/faasm/faasm.git"
    dest: "{{ ansible_env.HOME }}/code"
    update: yes
    clone: yes
