---

- name: "System deps"
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python3-dev
      - python3-pip
      - python3-venv
    update_cache: yes

- name: "Update pip"
  become: yes
  shell: "pip3 install -U pip"

