---

- name: "System deps"
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - pass
      - software-properties-common
      - linux-generic-hwe-20.04
    update_cache: yes

- name: "Create code dir"
  file:
    path: "/home/{{ ansible_ssh_user }}/code"
    state: directory

- name: "Clone repos"
  git:
    repo: "https://www.github.com/faasm/{{ item }}.git"
    dest: "/home/{{ ansible_ssh_user }}/code/{{ item }}"
    depth: 1
    update: yes
    clone: yes
    force: yes
    accept_hostkey: yes
  with_items:
    - "faasm"
    - "experiment-base"
