---

- name: "Create code dir"
  file:
    path: "/home/{{ ansible_user }}/code"
    state: directory

- name: "Clone repos"
  git:
    repo: "https://www.github.com/faasm/{{ item }}.git"
    dest: "/home/{{ ansible_user }}/code/{{ item }}"
    depth: 1
    update: yes
    recursive: no
    clone: yes
    force: yes
    accept_hostkey: yes
  with_items:
    - "faasm"
    - "experiment-base"

- name: "Clone specific Faasm submodules"
  shell: "git submodule update --init {{ item }}"
  args:
    chdir: "/home/{{ ansible_user }}/code/faasm"
  with_items:
    - "clients/cpp"
    - "clients/python"
    - "faabric"

- name: "Clone specific experiment submodules"
  shell: "git submodule update --init {{ item }}"
  args:
    chdir: "/home/{{ ansible_user }}/code/experiment-base"
  with_items:
    - "experiments/sgx"

