---

- name: "Add Docker GPG key"
  become: yes
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: "Add Docker APT repository"
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"

- name: "Install Docker"
  become: yes
  apt:
    name: docker-ce
    update_cache: yes

- name: "Add user to docker group"
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: "Install docker-compose"
  become: yes
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
