---

- name: "Make sure snap is installed"
  become: yes
  apt:
    name:
      - snapd
    update_cache: yes

- name: "Install microk8s"
  become: yes
  snap:
    name: microk8s
    classic: yes
    channel: 1.18/stable

- name: "Add user to group"
  become: yes
  user: name={{ ansible_ssh_user }} groups=microk8s append=yes

- name: "Print sudo user"
  become: yes
  debug:
    var: ansible_ssh_user

- name: "Change kube dir file permission"
  become: yes
  file:
    path: "/home/{{ ansible_ssh_user }}/.kube"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    recurse: yes

- name: "Alias kubectl"
  become: yes
  shell: "snap alias microk8s.kubectl kubectl"

- name: "Wait for microk8s to be ready"
  shell: "microk8s status --wait-ready"

- name: "Enable microk8s plugins"
  shell: "microk8s.enable dns rbac ingress"
