---

- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - include_tasks: tasks/base.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/microk8s.yml

- hosts: main
  tasks:
    - name: "Run add-node command"
      shell: "microk8s add-node"
      when : "'main' in group_names"
      register: join_output

    - name: "Extract join command"
      set_fact:
        join: "{{ join_output.stdout_lines[3] }}"

    - name: "Print join command"
      debug:
        var: join

    - name: "Create kube dir"
      delegate_to: localhost
      file:
        path: "{{ lookup('env','HOME') }}/.kube"
        state: directory

    - name: "Run kubectl config command"
      shell: "microk8s config"
      register: kubectl_config

    - name: "Download kubectl"
      delegate_to: localhost
      copy:
        content: "{{ kubectl_config.stdout }} "
        dest: "{{ lookup('env','HOME') }}/.kube/config"

- hosts: worker
  tasks:
    - name: "Run join command from worker"
      become: yes
      shell: "{{ hostvars[groups['main'][0]]['join'] }}"
