name: Formatting Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  python-format:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # --- Formatting checks ---
      - name: "Python formatting check"
        run: ./bin/inv_wrapper.sh format-code
